import '../styles/globals.css'
import './head'
//import {ContextProvider} from '../app/context/store'
export const metadata = {
  title: 'Experteam AI',
  description: 'Generated by Next.js',
  keywords: ['Experteam', 'AI', 'Writer'],
  icons: {
    icon: '/favicon.ico',

  },
}




export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="he" dir='rtl'>
      <head/>
      <body>
      
        {children}
      
        </body>
    </html>
  )
}
